### PR TITLE
Issue 15: Made about.html responsive

### LINKED ISSUE #15: SeatAndEat : Change Styles Of About Us Page
- Make about us section responsive

### PR DESCRIPTION
**Pull request by iamatifmoin**
## Linked Issue 

Closes: #15 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

@Rupam-Matabber The last PR was causing some problems so I made this new PR with no conflicts.
I have also made all the changes that you suggested.

### CODE REVIEW

**Review by Rupam-Matabber — COMMENTED** [review]
image

What is this @iamatifmoin ?

- Fix the bugs. use max-width property instead of min-width.

- Also, turn off the animation of the image for smaller screens.

- Make sure that there are no bugs while making the pr.

**Comment by iamatifmoin** [comment]
@Rupam-Matabber I had actually forgotten to make some commits to the branch.
I have made the suggested changes and fixed the bugs.

Note-> The max-width property is causing some errors so I have used the min-width property instead.

**Comment by Rupam-Matabber** [comment]
@iamatifmoin please record a video of the responsiveness of the about page and show me by replying to this comment.
The bugs are still there. Please recheck.

**Comment by iamatifmoin** [comment]
@Rupam-Matabber This is the video. It is a bit laggy.

Can you tell me what are the bugs? Because it is running smoothly on my computer.

[About-us.webm](https://user-images.githubusercontent.com/97212195/181879033-5b10581b-f7b0-4f5a-8f5f-256f1f1f0363.webm)

**Comment by Rupam-Matabber** [comment]
@iamatifmoin You are doing exactly the opposite of the desired design. I also told you to turn off the animation for smaller screens but you turned it off for larger screens. So, I am telling you what exactly you have to do. Read carefully.

- See the design of the about page from the hosted link. Don't change the design for larger screens. It is perfect. the image is supposed to be on the left side and the text container should be on the right side for larger screens.
- For smaller screens, the image is supposed to be on the top and the text container should be on the bottom.
- Also turn off the animation of the image for smaller screens.
- Adjust the padding, margin, font size of the text and heading, and the size of the image for smaller screens. Reduce them perfectly.
- 
image
This is the desired design for larger screens. 

- I will suggest you to use the max-width property. It will make your task easy.

**Comment by iamatifmoin** [comment]
@Rupam-Matabber Please review these changes.

[About-us-new.webm](https://user-images.githubusercontent.com/97212195/181902767-081e1b05-2901-40cd-8c77-7595ca1983bc.webm)

**Review by Rupam-Matabber — COMMENTED** [review]
image
The final design should look like this. make the image a little bigger.

 I am giving you some suggestions.

- Add max-width 100% and max-height 15% to the image wrapper div inside the media query.
- Change the position of the text wrapper div from absolute to static inside the media query.

@iamatifmoin make this changes and your pr will be ready to be merged.

**Comment by iamatifmoin** [comment]
@Rupam-Matabber I have made some changes. Please review.

**Pull request merged**
