### PR TITLE
i can change contact page..

### PR DESCRIPTION
**Pull request by sudip004**
Screenshot (11)
## Linked Issue 

Closes: #issue number that will be closed through this PR

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [1 ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Rupam-Matabber** [comment]
The design of the contact page is already good and this issue is also against the norms of KSoC.

**Comment by sudip004** [comment]
Hey, i am beginner..so can you tell me what I can do

**Comment by sudip004** [comment]
What are the chances i can perform to improve your project

**Comment by Rupam-Matabber** [comment]
@sudip004 Don't worry we will let you know if there are some design changes. 
You can check the issues which are not assigned to someone and have the label KSoC'22.
You can also check our other projects as well.

**Pull request closed without merging**
