### PR TITLE
Issue 15 resolved

### PR DESCRIPTION
**Pull request by ahmedbilal-2711**
## Linked Issue 15

Closes: #issue number that will be closed through this PR

### Describe the changes you've made
Made the about us page responsive

Give a clear description what modifications you have made
Add flex flow column on mobile screen and adjusted content

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Rupam-Matabber** [comment]
Which issue is this @ahmedbilal-2711

**Comment by ahmedbilal-2711** [comment]
@Rupam-Matabber Made about us responsive

**Comment by ahmedbilal-2711** [comment]
> Which issue is this @ahmedbilal-2711

Any updates?

**Comment by Rupam-Matabber** [comment]
@ahmedbilal-2711 issue no 15 was already resolved by someone else because he was assigned to do that. You can not work on any issue without the permission of the project maintainer. It is good that you made the pull request but you need to be assigned to that particular issue before working. You should read the KSoC guidelines carefully. So, I am closing this pull request.

**Pull request closed without merging**
