### PR TITLE
responsive carousel

### PR DESCRIPTION
**Pull request by ahmedbilal-2711**
Issue #14 resolved

### CODE REVIEW

**Comment by Rupam-Matabber** [comment]
Please follow the KSoC guidelines and use the PR template. Also, share screenshots of your work.

**Comment by Rupam-Matabber** [comment]
@ahmedbilal-2711 Please follow the KSoC guidelines and use the PR template. Also, share screenshots of your work.

**Comment by ahmedbilal-2711** [comment]
@Rupam-Matabber Can you please help me find the guidelines and PR template.

**Comment by Rupam-Matabber** [comment]
@ahmedbilal-2711 The PR template will automatically come when you are going to create a pull request. You have to edit it according to you and there is a section for attaching screenshots.  

But unfortunately, I have to close this PR because you worked on a different issue. You are assigned issue #14 . But you have not done it.

**Pull request closed without merging**
